<?php
$last = null;
$subjects = $counts = array();

for ($year = date('Y', RankData::search(array('board' => $this->board))->min('time')->time); $year <= date('Y', RankData::search(array('board' => $this->board))->max('time')->time); $year ++) {
    foreach (CacheData::getData($this->board, 0, $year) as $data) {
        list($t, $c, $n) = $data;
        $counts[] = array($t * 1000, $c);
    }
    foreach (TitleHistory::search(array('board' => $this->board))->search("`time` >= " . mktime(0, 0, 0, 1, 1, $year) . ' AND `time` < ' . mktime(0, 0, 0, 1, 1, $year + 1))->order("time ASC")->toArray(array('time', 'title')) as $titlehistory) {
        $subjects[] = array(intval($titlehistory['time']), $titlehistory['title']);
    }
}
$this->title = $this->board . ' @ ';
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript" src="/static/jquery-flot/flot/jquery.flot.js"></script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>
<div class="span6">
看版: <?= $this->escape($this->board) ?><br>
<hr>
<div id="placeholder" style="width:100%;height:300px;"></div>
時間: <span id="time"></span><br>
人氣: <span id="count"></span><br>
標題: <span id="subject"></span><br>
<script type="text/javascript">
$(function () {
    var counts = <?= json_encode($counts) ?>;
    var week_day = {0: '日', 1: '一', 2: '二', 3: '三', 4: '四', 5: '五', 6: '六'};

    var get_time = function(v){
	var d = new Date();
	d.setTime(v);
	return d.getUTCFullYear() + '/' + (d.getMonth() + 1) + "/" + d.getDate() + '(' + week_day[d.getDay()] + ')' + d.getHours() + ':' + d.getMinutes();
    };


    var draw_plot = function(){
    $.plot($("#placeholder"), [ counts ], {
	grid: { hoverable: true },
	xaxis: { mode: 'time', tickFormatter: function (v, axis) {
	    var ret = get_time(v);
	    return ret;
	}}
    });
    };

    $(draw_plot);
    $(window).resize(draw_plot);

    $("#placeholder").bind("plothover", function (event, pos, item) {
	if (item) {
	    $('#time').text(get_time(item.datapoint[0].toFixed()));
            $('#count').text(item.datapoint[1].toFixed());
            $('#title-history li').each(function(){
                if (parseInt($(this).attr('data-timestamp'), 10) * 1000 >= item.datapoint[0].toFixed()) {
                    $('#subject').text($(this).attr('data-title'));
                    return false;
                }
            });
	}
    });

});
</script>
<script type="text/javascript"><!--
google_ad_client = "ca-pub-3389357009051920";
/* PTT Hot */
google_ad_slot = "4781226853";
google_ad_width = 728;
google_ad_height = 90;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<div class="fb-comments" data-href="http://hot.pttt.tw/board/<?= $this->board ?>" data-width="470" data-num-posts="2"></div>
</div>
<div class="span4">
<h2>標題記錄</h2>
<ul id="title-history">
    <?php foreach ($subjects as $time_title) { ?>
    <?php list($time, $title) = $time_title; ?>
    <li data-title="<?= $this->escape($title) ?>" data-timestamp="<?= $time ?>"><?= date('Y/m/d H:i:s', $time) ?>: <?= $this->escape($title) ?></li>
    <?php } ?>
</ul>
</div>
<?= $this->partial('/common/footer.phtml', $this) ?>
