<?php
$last = null;
$subjects = $counts = array();

if ($this->from and $this->to) {
    foreach (RankData::search(array('board' => $this->board))->search("{$this->from} < time AND time < {$this->to}")->order('time ASC') as $rd) {
        $counts[] = array($rd->time * 1000, intval($rd->count));
    }
    foreach (TitleHistory::search(array('board' => $this->board))->search("{$this->from} < time AND time < {$this->to}")->order('time ASC') as $th) {
        $subjects[] = array($th->time, $th->title);
    }
} else {
    for ($year = date('Y', RankData::search(array('board' => $this->board))->min('time')->time); $year <= date('Y', RankData::search(array('board' => $this->board))->max('time')->time); $year ++) {
        foreach (CacheData::getData($this->board, 0, $year) as $data) {
            list($t, $c, $n) = $data;
            $counts[] = array($t * 1000, intval($c));
        }
        foreach (TitleHistory::search(array('board' => $this->board))->search("`time` >= " . mktime(0, 0, 0, 1, 1, $year) . ' AND `time` < ' . mktime(0, 0, 0, 1, 1, $year + 1))->order("time ASC")->toArray(array('time', 'title')) as $titlehistory) {
            $subjects[] = array(intval($titlehistory['time']), $titlehistory['title']);
        }
    }
}
$this->title = $this->board . ' @ ';
$first_sunday = strtotime('last sunday 0:0:0', $counts[0][0] / 1000);
$last_sunday = strtotime('next sunday 0:0:0', $counts[count($counts) - 1][0] / 1000);
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<style>
.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

.x.axis path {
  display: none;
}

.line {
  fill: none;
  stroke: steelblue;
  stroke-width: 1.5px;
}

</style>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script src="//d3js.org/d3.v3.min.js"></script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>
<div class="span6" style="min-width: 768px">
看版: <?= $this->escape($this->board) ?><br>
<hr>
<div id="placeholder" style="width:100%;height:300px;"></div>
時間: <span id="time"></span><br>
人氣: <span id="count"></span><br>
標題: <span id="subject"></span><br>
<script type="text/javascript">
var week_day = {0: '日', 1: '一', 2: '二', 3: '三', 4: '四', 5: '五', 6: '六'};

var margin = {top: 20, right: 20, bottom: 30, left: 50},
    width = 800 - margin.left - margin.right,
    height = 300 - margin.top - margin.bottom;

var x = d3.time.scale()
    .range([0, width]);

var y = d3.scale.linear()
    .range([height, 0]);

var xAxis = d3.svg.axis()
    .scale(x)
    .orient("bottom");

var yAxis = d3.svg.axis()
    .scale(y)
    .orient("left");

var line = d3.svg.line()
    .x(function(d) { return x(d[0]); })
    .y(function(d) { return y(d[1]); });

var svg = d3.select("#placeholder").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");
    var first_sunday = <?= intval($first_sunday) ?>;
    var last_sunday = <?= intval($last_sunday) ?>;
data = <?= json_encode($counts) ?>;
  x.domain(d3.extent(data, function(d) { return d[0]; }));
  y.domain(d3.extent(data, function(d) { return d[1]; }));

  svg.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis);

  svg.append("g")
      .attr("class", "y axis")
      .call(yAxis)
    .append("text")
      .attr("transform", "rotate(-90)")
      .attr("y", 6)
      .attr("dy", ".71em")
      .style("text-anchor", "end")
      .text("人氣");

  var get_time = function(t){
      d = new Date;
      d.setTime(t);
      return d.getUTCFullYear() + '/' + (d.getMonth() + 1) + "/" + d.getDate() + '(' + week_day[d.getDay()] + ')' + d.getHours() + ':' + d.getMinutes();
  };

    bisectDate = d3.bisector(function(d) { return d[0]; }).left,

  svg.append("path")
      .datum(data)
      .attr("class", "line")
      .attr("d", line)
      .on('mousemove', function(d, i){
          var d = x.invert(d3.mouse(this)[0]);
          var mouse_value = y.invert(d3.mouse(this)[1]);
          var c = bisectDate(data, d, 1);
          var min_count = c;
          for (var i = c - 3; i < c + 3; i ++) {
              if (Math.abs(mouse_value - data[i][1]) < Math.abs(data[min_count][1] - mouse_value)) {
                  min_count = i;
                  $('#count').text(data[i][1]);
                  d = data[i][0];
                  $('#time').text(get_time(data[i][0]));
              }
          }
          $('#title-history li').each(function(){
              if (parseInt($(this).attr('data-timestamp'), 10) * 1000 >= d) {
                  $('#subject').text($(this).attr('data-title'));
                  return false;
                  }
          });
      })

      for (var sunday_time = first_sunday; sunday_time <= last_sunday; sunday_time += 86400 * 7) {
          weekend_left  = x((new Date).setTime(1000 * sunday_time - 86400 * 1000 * 2));
          weekend_left = Math.max(weekend_left, 0);
          weekend_right = x((new Date).setTime(1000 * sunday_time));
          if (weekend_right < 0) {
              continue;
          }
          weekend_width = weekend_right - weekend_left;

              svg.append('rect').attr({
                  width: weekend_width,
                  height: height,
                  x: Math.max(weekend_left, 0),
                  y: 0,
                  opacity: 0.3,
                  fill: 'rgb(255,0,0',
              });
          }

function type(d) {
  d[0] = new Date(d[0]);
  return d;
}

</script>
<script type="text/javascript"><!--
google_ad_client = "ca-pub-3389357009051920";
/* PTT Hot */
google_ad_slot = "4781226853";
google_ad_width = 728;
google_ad_height = 90;
//-->
</script>
<script type="text/javascript"
src="//pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<div class="fb-comments" data-href="http://ptthot.ronny.tw/board/<?= $this->board ?>" data-width="470" data-num-posts="2"></div>
</div>
<div class="span4">
<h2>標題記錄</h2>
<ul id="title-history">
    <?php foreach ($subjects as $time_title) { ?>
    <?php list($time, $title) = $time_title; ?>
    <li data-title="<?= $this->escape($title) ?>" data-timestamp="<?= $time ?>"><?= date('Y/m/d H:i:s', $time) ?>: <?= $this->escape($title) ?></li>
    <?php } ?>
</ul>
</div>
<?= $this->partial('/common/footer.phtml', $this) ?>
