<?php
$last = null;
$subjects = $counts = $changed = array();
foreach (RankData::search(array('board' => $this->board))->order(array('time' => 'asc')) as $d) { 
    $counts[] = array($d->time * 1000, $d->count);
    $subjects[$d->time * 1000] = $d->name;
    if (is_null($last) or $d->name != $last) { 
	$changed[$d->time * 1000] = $d->name;
    }
    $last = $d->name;
}
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript" src="/static/jquery-flot/flot/jquery.flot.js"></script>

看版: <?= $this->escape($this->board) ?><br>
<hr>
<div id="placeholder" style="width:600px;height:300px;"></div>
時間: <span id="time"></span><br>
人氣: <span id="count"></span><br>
標題: <span id="subject"></span><br>
<script type="text/javascript">
$(function () {
    var counts = <?= json_encode($counts) ?>;
    var subjects = <?= json_encode($subjects) ?>;
    var week_day = {0: '日', 1: '一', 2: '二', 3: '三', 4: '四', 5: '五', 6: '六'};

    var get_time = function(v){
	var d = new Date();
	d.setTime(v);
	return (d.getMonth() + 1) + "/" + d.getDate() + '(' + week_day[d.getDay()] + ')' + d.getHours() + ':' + d.getMinutes();
    };


    $.plot($("#placeholder"), [ counts ], {
	grid: { hoverable: true },
	xaxis: { mode: 'time', tickFormatter: function (v, axis) {
	    var ret = get_time(v);
	    return ret;
	}}
    });

    $("#placeholder").bind("plothover", function (event, pos, item) {
	if (item) {
	    $('#time').text(get_time(item.datapoint[0].toFixed()));
	    $('#count').text(item.datapoint[1].toFixed());
	    if (subjects[item.datapoint[0].toFixed()]) {
		$('#subject').text(subjects[item.datapoint[0].toFixed()]);
	    }
	}
    });

});
</script>
<ol>
</ol>
<?= $this->partial('/common/footer.phtml', $this) ?>
