<?php
$latest_hots = json_decode(KeyValue::get('latest_hot'));
$latesttime = $latest_hots->time;
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<div class="span10">
最新時間: <?= date('Y/m/d H:i:s', $latesttime) ?><br>
<ol>
    <?php foreach ($latest_hots->boards as $board_count_name) { ?>
    <?php list($board, $count, $name) = $board_count_name; ?>
    <li>
    <a href="/board/<?= urlencode($board) ?>"><?= $this->escape($board) ?>. <?= $this->escape($name) ?></a> 人氣: <?= intval($count) ?>
    </li>
    <?php } ?>
</ol>
</div>
<?= $this->partial('/common/footer.phtml', $this) ?>
