<?php
$latesttime = WebBackup::search(1)->max('time')->time;
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<ol>
    <?php foreach (RankData::search(array('time' => $latesttime))->order(array('count' => 'desc')) as $data) { ?>
    <li>
    <a href="/board/<?= urlencode($data->board) ?>"><?= $this->escape($data->board) ?>. <?= $this->escape($data->name) ?></a> 人氣: <?= intval($data->count) ?>
    </li>
    <?php } ?>
</ol>
<?= $this->partial('/common/footer.phtml', $this) ?>
