<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title><?= $this->escape($this->title) ?>PTT 熱門記錄</title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.2.2/bootstrap.min.js"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.2.2/css/bootstrap.css">
<?php if (getenv('GOOGLEANALYTICS_ACCOUNT')) { ?>
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', <?= json_encode(getenv('GOOGLEANALYTICS_ACCOUNT')) ?>]);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<?php } ?>
</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="/">PTT 熱門記錄</a>
        <ul class="nav">
            <li>
            <a href="/">首頁</a>
            </li>
            <li>
            <a href="http://ronnywang-ptthot.s3-website-ap-northeast-1.amazonaws.com/" target="_blank">資料打包</a>
            </li>
            <li>
            <a href="http://www.ptt.cc/hotboard" target="_blank">資料來源</a>
            </li>
            <li>
            <a href="http://ronnywang.pixnet.net/blog" target="_blank">@ronnywang</a>
            </li>
        </ul>
        <form class="navbar-search pull-left" method="get" action="/index/search">
            <input type="text" class="search-query" name="q" placeholder="輸入想要搜尋的版名">
            <button type="submit">搜尋</button>
        </form>
    </div>
</div>
<div class="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <strong>
          2013/9/11 ~ 2013/9/24 資料因程式錯誤未抓到 Q_Q<br>
          2014/6/22 ~ 2014/7/22 因為 PTT 強制改成 https 程式未更新到 Q_Q
      </strong>
  </div>

<div class="container-fluid">
    <div class="row-fluid">
